# Generated by Django 3.1 on 2021-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
    ]
