# Generated by Django 3.1 on 2021-06-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210527_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/empty.png', null=True, upload_to='product/%Y/%m'),
        ),
    ]
