# Generated by Django 3.1 on 2021-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210603_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/empty.png', null=True, upload_to='product/%Y/%m'),
        ),
    ]
